// <auto-generated />
// Generated by scripts/generate_assetlink_sdks.py; contract 17d4f9a6e719b4739e143d67b061524386f65be3fc7475a96b0b316b8e43a29e.
@file:Suppress("MagicNumber", "TooManyFunctions")

package app.assetlibrary.assetlink

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.boolean
import kotlinx.serialization.json.int
import kotlinx.serialization.json.jsonPrimitive

public enum class AssetLinkMessageKind {
    CONTROL_CANCEL,
    CONTROL_RESULT,
    CONTROL_REQUEST,
    DOWNLOAD_RANGE,
    DOWNLOAD_RESULT,
    ERROR,
    EVENT,
    HANDSHAKE_RESPONSE,
    HANDSHAKE_REQUEST,
    EVENT_REPLAY_REQUEST,
    EVENT_REPLAY_RESULT,
    UPLOAD_CANCEL_RESULT,
    UPLOAD_CANCEL,
    UPLOAD_CHUNK_RESULT,
    UPLOAD_CHUNK,
    UPLOAD_COMPLETE_RESULT,
    UPLOAD_COMPLETE,
    UPLOAD_CREATE,
    UPLOAD_CREATED,
    UPLOAD_STATUS,
    UNKNOWN,
}

public object AssetLinkMessageTypes {
    public const val CONTROL_CANCEL: String = "control.cancel"
    public const val CONTROL_RESULT: String = "control.result"
    public const val CONTROL_REQUEST: String = "control.request"
    public const val DOWNLOAD_RANGE: String = "download.range"
    public const val DOWNLOAD_RESULT: String = "download.result"
    public const val ERROR: String = "error"
    public const val EVENT: String = "event"
    public const val HANDSHAKE_RESPONSE: String = "handshake.response"
    public const val HANDSHAKE_REQUEST: String = "handshake.request"
    public const val EVENT_REPLAY_REQUEST: String = "event.replay.request"
    public const val EVENT_REPLAY_RESULT: String = "event.replay.result"
    public const val UPLOAD_CANCEL_RESULT: String = "upload.cancel.result"
    public const val UPLOAD_CANCEL: String = "upload.cancel"
    public const val UPLOAD_CHUNK_RESULT: String = "upload.chunk.result"
    public const val UPLOAD_CHUNK: String = "upload.chunk"
    public const val UPLOAD_COMPLETE_RESULT: String = "upload.complete.result"
    public const val UPLOAD_COMPLETE: String = "upload.complete"
    public const val UPLOAD_CREATE: String = "upload.create"
    public const val UPLOAD_CREATED: String = "upload.created"
    public const val UPLOAD_STATUS: String = "upload.status"
}

public abstract class AssetLinkMessage(public val raw: JsonObject) {
    public val messageType: String get() = raw.getRequiredString("message_type")

    public fun encode(): String = raw.toString()
}

public class UnknownAssetLinkMessage(raw: JsonObject) : AssetLinkMessage(raw)

public object AssetLinkCodec {
    public fun parse(input: String): AssetLinkMessage {
        val root = Json.parseToJsonElement(input) as? JsonObject
            ?: throw IllegalArgumentException("AssetLink message must be a JSON object.")
        return when (root.getRequiredString("message_type")) {
        "control.cancel" -> ControlCancelMessage(root)
        "control.result" -> ControlResultMessage(root)
        "control.request" -> ControlRequestMessage(root)
        "download.range" -> DownloadRangeMessage(root)
        "download.result" -> DownloadResultMessage(root)
        "error" -> ErrorMessage(root)
        "event" -> EventMessage(root)
        "handshake.response" -> HandshakeResponseMessage(root)
        "handshake.request" -> HandshakeRequestMessage(root)
        "event.replay.request" -> EventReplayRequestMessage(root)
        "event.replay.result" -> EventReplayResultMessage(root)
        "upload.cancel.result" -> UploadCancelResultMessage(root)
        "upload.cancel" -> UploadCancelMessage(root)
        "upload.chunk.result" -> UploadChunkResultMessage(root)
        "upload.chunk" -> UploadChunkMessage(root)
        "upload.complete.result" -> UploadCompleteResultMessage(root)
        "upload.complete" -> UploadCompleteMessage(root)
        "upload.create" -> UploadCreateMessage(root)
        "upload.created" -> UploadCreatedMessage(root)
        "upload.status" -> UploadStatusMessage(root)
            else -> UnknownAssetLinkMessage(root)
        }
    }

    public fun classify(messageType: String): AssetLinkMessageKind = when (messageType) {
        "control.cancel" -> AssetLinkMessageKind.CONTROL_CANCEL
        "control.result" -> AssetLinkMessageKind.CONTROL_RESULT
        "control.request" -> AssetLinkMessageKind.CONTROL_REQUEST
        "download.range" -> AssetLinkMessageKind.DOWNLOAD_RANGE
        "download.result" -> AssetLinkMessageKind.DOWNLOAD_RESULT
        "error" -> AssetLinkMessageKind.ERROR
        "event" -> AssetLinkMessageKind.EVENT
        "handshake.response" -> AssetLinkMessageKind.HANDSHAKE_RESPONSE
        "handshake.request" -> AssetLinkMessageKind.HANDSHAKE_REQUEST
        "event.replay.request" -> AssetLinkMessageKind.EVENT_REPLAY_REQUEST
        "event.replay.result" -> AssetLinkMessageKind.EVENT_REPLAY_RESULT
        "upload.cancel.result" -> AssetLinkMessageKind.UPLOAD_CANCEL_RESULT
        "upload.cancel" -> AssetLinkMessageKind.UPLOAD_CANCEL
        "upload.chunk.result" -> AssetLinkMessageKind.UPLOAD_CHUNK_RESULT
        "upload.chunk" -> AssetLinkMessageKind.UPLOAD_CHUNK
        "upload.complete.result" -> AssetLinkMessageKind.UPLOAD_COMPLETE_RESULT
        "upload.complete" -> AssetLinkMessageKind.UPLOAD_COMPLETE
        "upload.create" -> AssetLinkMessageKind.UPLOAD_CREATE
        "upload.created" -> AssetLinkMessageKind.UPLOAD_CREATED
        "upload.status" -> AssetLinkMessageKind.UPLOAD_STATUS
        else -> AssetLinkMessageKind.UNKNOWN
    }
}

public object AssetLinkUInt64 {
    private const val MAXIMUM: String = "18446744073709551615"
    private val canonical = Regex("^(0|[1-9][0-9]*)$")

    public fun parse(value: String): ULong {
        require(value.length <= 20 && canonical.matches(value)) {
            "AssetLink uint64 must be a canonical decimal value in range."
        }
        require(value.length < 20 || value <= MAXIMUM) {
            "AssetLink uint64 must be a canonical decimal value in range."
        }
        return value.toULong()
    }

    public fun format(value: ULong): String = value.toString()
}

private fun JsonObject.getRequiredPrimitive(name: String): JsonPrimitive =
    this[name] as? JsonPrimitive ?: throw IllegalArgumentException("Required AssetLink field is missing: $name")

private fun JsonObject.getOptionalPrimitive(name: String): JsonPrimitive? {
    val value = this[name] ?: return null
    return value as? JsonPrimitive ?: throw IllegalArgumentException("AssetLink field $name must be a primitive.")
}

private fun JsonPrimitive.requireString(name: String): String {
    require(isString) { "AssetLink field $name must be a string." }
    return content
}

private fun JsonPrimitive.requireNonString(name: String): JsonPrimitive {
    require(!isString) { "AssetLink field $name must not be a string." }
    return this
}

private fun JsonObject.getRequiredString(name: String): String = getRequiredPrimitive(name).requireString(name)

private fun JsonObject.getOptionalString(name: String): String? = getOptionalPrimitive(name)?.requireString(name)

private fun JsonObject.getRequiredInt(name: String): Int = getRequiredPrimitive(name).requireNonString(name).int

private fun JsonObject.getOptionalInt(name: String): Int? = getOptionalPrimitive(name)?.requireNonString(name)?.int

private fun JsonObject.getRequiredBoolean(name: String): Boolean =
    getRequiredPrimitive(name).requireNonString(name).boolean

private fun JsonObject.getOptionalBoolean(name: String): Boolean? =
    getOptionalPrimitive(name)?.requireNonString(name)?.boolean

private fun JsonObject.getRequiredObject(name: String): JsonObject =
    this[name] as? JsonObject ?: throw IllegalArgumentException("AssetLink field $name must be an object.")

private fun JsonObject.getOptionalObject(name: String): JsonObject? {
    val value = this[name] ?: return null
    return value as? JsonObject ?: throw IllegalArgumentException("AssetLink field $name must be an object.")
}

private fun JsonObject.getRequiredStringList(name: String): List<String> =
    (this[name] as? JsonArray)?.map { it.jsonPrimitive.requireString(name) }
        ?: throw IllegalArgumentException("AssetLink field $name must be a string array.")

private fun JsonObject.getOptionalStringList(name: String): List<String>? {
    val value = this[name] ?: return null
    return (value as? JsonArray)?.map { it.jsonPrimitive.requireString(name) }
        ?: throw IllegalArgumentException("AssetLink field $name must be a string array.")
}

private fun JsonObject.getRequiredObjectList(name: String): List<JsonObject> =
    (this[name] as? JsonArray)?.map { it as JsonObject }
        ?: throw IllegalArgumentException("AssetLink field $name must be an object array.")

private fun JsonObject.getOptionalObjectList(name: String): List<JsonObject>? {
    val value = this[name] ?: return null
    return (value as? JsonArray)?.map {
        it as? JsonObject ?: throw IllegalArgumentException("AssetLink field $name must be an object array.")
    } ?: throw IllegalArgumentException("AssetLink field $name must be an object array.")
}


public class ControlCancelMessage(raw: JsonObject) : AssetLinkMessage(raw) {
    public companion object { public const val WIRE_MESSAGE_TYPE: String = "control.cancel" }

    public val requestId: String get() = raw.getRequiredString("request_id")

    public val cancelOf: String get() = raw.getRequiredString("cancel_of")
}

public class ControlResultMessage(raw: JsonObject) : AssetLinkMessage(raw) {
    public companion object { public const val WIRE_MESSAGE_TYPE: String = "control.result" }

    public val requestId: String get() = raw.getRequiredString("request_id")

    public val ok: Boolean get() = raw.getRequiredBoolean("ok")

    public val body: JsonObject get() = raw.getRequiredObject("body")
}

public class ControlRequestMessage(raw: JsonObject) : AssetLinkMessage(raw) {
    public companion object { public const val WIRE_MESSAGE_TYPE: String = "control.request" }

    public val requestId: String get() = raw.getRequiredString("request_id")

    public val operation: String get() = raw.getRequiredString("operation")

    public val body: JsonObject get() = raw.getRequiredObject("body")

    public val idempotencyKey: String? get() = raw.getOptionalString("idempotency_key")

    public val timeoutMs: Int? get() = raw.getOptionalInt("timeout_ms")

    public val cancelOf: String? get() = raw.getOptionalString("cancel_of")
}

public class DownloadRangeMessage(raw: JsonObject) : AssetLinkMessage(raw) {
    public companion object { public const val WIRE_MESSAGE_TYPE: String = "download.range" }

    public val assetId: String get() = raw.getRequiredString("asset_id")

    public val start: String get() = raw.getRequiredString("start")

    public val end: String get() = raw.getRequiredString("end")
}

public class DownloadResultMessage(raw: JsonObject) : AssetLinkMessage(raw) {
    public companion object { public const val WIRE_MESSAGE_TYPE: String = "download.result" }

    public val length: String get() = raw.getRequiredString("length")

    public val start: String get() = raw.getRequiredString("start")

    public val end: String get() = raw.getRequiredString("end")

    public val contentSha256: String get() = raw.getRequiredString("content_sha256")

    public val readable: Boolean get() = raw.getRequiredBoolean("readable")

    public val verified: Boolean get() = raw.getRequiredBoolean("verified")
}

public class ErrorMessage(raw: JsonObject) : AssetLinkMessage(raw) {
    public companion object { public const val WIRE_MESSAGE_TYPE: String = "error" }

    public val requestId: String get() = raw.getRequiredString("request_id")

    public val error: JsonObject get() = raw.getRequiredObject("error")
}

public class EventMessage(raw: JsonObject) : AssetLinkMessage(raw) {
    public companion object { public const val WIRE_MESSAGE_TYPE: String = "event" }

    public val eventId: String get() = raw.getRequiredString("event_id")

    public val eventType: String get() = raw.getRequiredString("event_type")

    public val cursor: String get() = raw.getRequiredString("cursor")

    public val sequence: String get() = raw.getRequiredString("sequence")

    public val occurredAt: String get() = raw.getRequiredString("occurred_at")

    public val payload: JsonObject get() = raw.getRequiredObject("payload")
}

public class HandshakeResponseMessage(raw: JsonObject) : AssetLinkMessage(raw) {
    public companion object { public const val WIRE_MESSAGE_TYPE: String = "handshake.response" }

    public val selectedVersion: String get() = raw.getRequiredString("selected_version")

    public val serverId: String get() = raw.getRequiredString("server_id")

    public val serverVersion: String get() = raw.getRequiredString("server_version")

    public val capabilities: List<String> get() = raw.getRequiredStringList("capabilities")

    public val endpointRole: String get() = raw.getRequiredString("endpoint_role")

    public val requestId: String? get() = raw.getOptionalString("request_id")
}

public class HandshakeRequestMessage(raw: JsonObject) : AssetLinkMessage(raw) {
    public companion object { public const val WIRE_MESSAGE_TYPE: String = "handshake.request" }

    public val client: JsonObject get() = raw.getRequiredObject("client")

    public val supportedVersions: List<String> get() = raw.getRequiredStringList("supported_versions")

    public val capabilities: List<String> get() = raw.getRequiredStringList("capabilities")

    public val endpointRole: String get() = raw.getRequiredString("endpoint_role")

    public val requestId: String? get() = raw.getOptionalString("request_id")
}

public class EventReplayRequestMessage(raw: JsonObject) : AssetLinkMessage(raw) {
    public companion object { public const val WIRE_MESSAGE_TYPE: String = "event.replay.request" }

    public val afterCursor: String get() = raw.getRequiredString("after_cursor")

    public val limit: Int get() = raw.getRequiredInt("limit")

    public val requestId: String get() = raw.getRequiredString("request_id")
}

public class EventReplayResultMessage(raw: JsonObject) : AssetLinkMessage(raw) {
    public companion object { public const val WIRE_MESSAGE_TYPE: String = "event.replay.result" }

    public val events: List<JsonObject> get() = raw.getRequiredObjectList("events")

    public val nextCursor: String get() = raw.getRequiredString("next_cursor")

    public val gap: Boolean get() = raw.getRequiredBoolean("gap")

    public val requestId: String get() = raw.getRequiredString("request_id")
}

public class UploadCancelResultMessage(raw: JsonObject) : AssetLinkMessage(raw) {
    public companion object { public const val WIRE_MESSAGE_TYPE: String = "upload.cancel.result" }

    public val requestId: String get() = raw.getRequiredString("request_id")

    public val transferId: String get() = raw.getRequiredString("transfer_id")

    public val cancelled: Boolean get() = raw.getRequiredBoolean("cancelled")
}

public class UploadCancelMessage(raw: JsonObject) : AssetLinkMessage(raw) {
    public companion object { public const val WIRE_MESSAGE_TYPE: String = "upload.cancel" }

    public val requestId: String get() = raw.getRequiredString("request_id")

    public val transferId: String get() = raw.getRequiredString("transfer_id")
}

public class UploadChunkResultMessage(raw: JsonObject) : AssetLinkMessage(raw) {
    public companion object { public const val WIRE_MESSAGE_TYPE: String = "upload.chunk.result" }

    public val requestId: String get() = raw.getRequiredString("request_id")

    public val transferId: String get() = raw.getRequiredString("transfer_id")

    public val offset: String get() = raw.getRequiredString("offset")

    public val accepted: Boolean get() = raw.getRequiredBoolean("accepted")

    public val duplicate: Boolean get() = raw.getRequiredBoolean("duplicate")
}

public class UploadChunkMessage(raw: JsonObject) : AssetLinkMessage(raw) {
    public companion object { public const val WIRE_MESSAGE_TYPE: String = "upload.chunk" }

    public val requestId: String get() = raw.getRequiredString("request_id")

    public val transferId: String get() = raw.getRequiredString("transfer_id")

    public val offset: String get() = raw.getRequiredString("offset")

    public val chunkSize: Int get() = raw.getRequiredInt("chunk_size")

    public val chunkSha256: String get() = raw.getRequiredString("chunk_sha256")
}

public class UploadCompleteResultMessage(raw: JsonObject) : AssetLinkMessage(raw) {
    public companion object { public const val WIRE_MESSAGE_TYPE: String = "upload.complete.result" }

    public val requestId: String get() = raw.getRequiredString("request_id")

    public val transferId: String get() = raw.getRequiredString("transfer_id")

    public val verified: Boolean get() = raw.getRequiredBoolean("verified")

    public val readable: Boolean get() = raw.getRequiredBoolean("readable")

    public val verifiedLength: String get() = raw.getRequiredString("verified_length")

    public val verifiedSha256: String get() = raw.getRequiredString("verified_sha256")
}

public class UploadCompleteMessage(raw: JsonObject) : AssetLinkMessage(raw) {
    public companion object { public const val WIRE_MESSAGE_TYPE: String = "upload.complete" }

    public val requestId: String get() = raw.getRequiredString("request_id")

    public val transferId: String get() = raw.getRequiredString("transfer_id")

    public val contentSha256: String get() = raw.getRequiredString("content_sha256")

    public val idempotencyKey: String get() = raw.getRequiredString("idempotency_key")
}

public class UploadCreateMessage(raw: JsonObject) : AssetLinkMessage(raw) {
    public companion object { public const val WIRE_MESSAGE_TYPE: String = "upload.create" }

    public val requestId: String get() = raw.getRequiredString("request_id")

    public val length: String get() = raw.getRequiredString("length")

    public val contentSha256: String get() = raw.getRequiredString("content_sha256")

    public val idempotencyKey: String get() = raw.getRequiredString("idempotency_key")
}

public class UploadCreatedMessage(raw: JsonObject) : AssetLinkMessage(raw) {
    public companion object { public const val WIRE_MESSAGE_TYPE: String = "upload.created" }

    public val requestId: String get() = raw.getRequiredString("request_id")

    public val transferId: String get() = raw.getRequiredString("transfer_id")

    public val length: String get() = raw.getRequiredString("length")
}

public class UploadStatusMessage(raw: JsonObject) : AssetLinkMessage(raw) {
    public companion object { public const val WIRE_MESSAGE_TYPE: String = "upload.status" }

    public val transferId: String get() = raw.getRequiredString("transfer_id")

    public val length: String get() = raw.getRequiredString("length")

    public val receivedRanges: List<JsonObject> get() = raw.getRequiredObjectList("received_ranges")
}
