from __future__ import annotations

import importlib.util
import json
import shutil
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

ROOT = Path(__file__).resolve().parents[2]
GENERATOR_PATH = ROOT / "scripts" / "generate_assetlink_sdks.py"


def load_generator():
    specification = importlib.util.spec_from_file_location("assetlink_generator", GENERATOR_PATH)
    if specification is None or specification.loader is None:
        raise RuntimeError("cannot load AssetLink generator")
    module = importlib.util.module_from_spec(specification)
    sys.modules[specification.name] = module
    specification.loader.exec_module(module)
    return module


generator = load_generator()


class AssetLinkSdkGenerationTests(unittest.TestCase):
    def test_committed_generation_is_current_and_deterministic(self) -> None:
        first = generator.generated_outputs()
        second = generator.generated_outputs()

        self.assertEqual(first, second)
        self.assertEqual(0, generator.check(first))
        self.assertEqual(7, len(first))
        self.assertTrue(all(b"\r" not in content for content in first.values()))

    def test_generation_manifest_shape_exactly_matches_canonical_schemas(self) -> None:
        expected_messages = generator.load_messages()
        expected_types = [message.message_type for message in expected_messages]
        manifest = json.loads(
            (ROOT / "packages" / "sdk" / "assetlink" / "generation-manifest.json").read_text(encoding="utf-8")
        )
        self.assertEqual(expected_types, [item["message_type"] for item in manifest["messages"]])
        for source, generated in zip(expected_messages, manifest["messages"], strict=True):
            self.assertEqual(source.schema_file, generated["schema_file"])
            self.assertEqual(source.document["required"], generated["required"])
            self.assertEqual(
                source.document["properties"],
                {name: value["schema"] for name, value in generated["properties"].items()},
            )

    def test_every_wire_message_is_emitted_in_every_target_source(self) -> None:
        sources = [
            ROOT / "packages" / "sdk" / "assetlink" / "dotnet" / "AssetLink.Generated.cs",
            ROOT / "packages" / "sdk" / "assetlink" / "typescript" / "src" / "generated.ts",
            ROOT
            / "packages"
            / "sdk"
            / "assetlink"
            / "kotlin"
            / "src"
            / "main"
            / "kotlin"
            / "app"
            / "assetlibrary"
            / "assetlink"
            / "AssetLink.Generated.kt",
        ]
        content = [path.read_text(encoding="utf-8") for path in sources]
        for message in generator.load_messages():
            for target_source in content:
                self.assertIn(f'"{message.message_type}"', target_source)
                for property_name in message.document["properties"]:
                    self.assertIn(property_name, target_source)
        for target_source in content:
            self.assertIn("Unknown", target_source)

    def test_check_rejects_missing_modified_and_extra_generated_files(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            temporary_root = Path(temporary)
            contract_root = temporary_root / "contracts" / "assetlink"
            sdk_root = temporary_root / "packages" / "sdk" / "assetlink"
            shutil.copytree(ROOT / "contracts" / "assetlink", contract_root)
            with (
                mock.patch.object(generator, "CONTRACT_ROOT", contract_root),
                mock.patch.object(generator, "SDK_ROOT", sdk_root),
            ):
                outputs = generator.generated_outputs()
                generator.write(outputs)
                self.assertEqual(0, generator.check(outputs))

                generated_source = sdk_root / "typescript" / "src" / "generated.ts"
                generated_source.write_text("// hand edit\n", encoding="utf-8")
                self.assertEqual(1, generator.check(outputs))
                generated_source.write_bytes(outputs[generated_source])

                extra = sdk_root / "dotnet" / "Extra.Generated.cs"
                extra.write_text("// <auto-generated />\n", encoding="utf-8")
                self.assertEqual(1, generator.check(outputs))
                extra.unlink()

                generated_source.unlink()
                self.assertEqual(1, generator.check(outputs))

    def test_contract_digest_is_independent_of_checkout_line_endings(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            lf = root / "lf"
            crlf = root / "crlf"
            lf.mkdir()
            crlf.mkdir()
            (lf / "contract.json").write_bytes(b'{\n  "value": true\n}\n')
            (crlf / "contract.json").write_bytes(b'{\r\n  "value": true\r\n}\r\n')

            self.assertEqual(generator.contract_digest(lf), generator.contract_digest(crlf))

    def test_generator_fails_closed_when_contract_catalog_is_incomplete(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            contract_root = Path(temporary) / "assetlink"
            shutil.copytree(ROOT / "contracts" / "assetlink", contract_root)
            (contract_root / "upload-status.schema.json").unlink()
            with mock.patch.object(generator, "CONTRACT_ROOT", contract_root):
                with self.assertRaisesRegex(ValueError, "expected 20 AssetLink envelopes"):
                    generator.load_messages()

    def test_generator_fails_closed_when_common_wire_kind_changes(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            contract_root = Path(temporary) / "assetlink"
            shutil.copytree(ROOT / "contracts" / "assetlink", contract_root)
            common_path = contract_root / "common.schema.json"
            common = json.loads(common_path.read_text(encoding="utf-8"))
            common["$defs"]["server_id"] = {"type": "object"}
            common_path.write_text(json.dumps(common), encoding="utf-8")

            with mock.patch.object(generator, "CONTRACT_ROOT", contract_root):
                with self.assertRaisesRegex(ValueError, "common schema definition kinds are unsupported"):
                    generator.load_messages()

    def test_generator_fails_closed_when_external_reference_is_unresolved(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            contract_root = Path(temporary) / "assetlink"
            shutil.copytree(ROOT / "contracts" / "assetlink", contract_root)
            request_path = contract_root / "handshake.schema.json"
            request = json.loads(request_path.read_text(encoding="utf-8"))
            request["properties"]["client"] = {"$ref": "missing.schema.json#/$defs/client"}
            request_path.write_text(json.dumps(request), encoding="utf-8")

            with mock.patch.object(generator, "CONTRACT_ROOT", contract_root):
                with self.assertRaisesRegex(ValueError, "unresolved schema reference"):
                    generator.load_messages()


if __name__ == "__main__":
    unittest.main()
