// <auto-generated />
// Generated by scripts/generate_assetlink_sdks.py; contract 90a1427c8d6c70614f8e329d69d2cfa4f0c8d9c09d857bbce929ed241a807d9c.
#nullable enable
using System.Collections.ObjectModel;
using System.Globalization;
using System.Text.Json;
using System.Text.Json.Nodes;

namespace AssetLibrary.AssetLink;

public enum AssetLinkMessageKind
{
    ControlCancel,
    ControlResult,
    ControlRequest,
    DownloadRange,
    DownloadResult,
    Error,
    Event,
    HandshakeResponse,
    HandshakeRequest,
    EventReplayRequest,
    EventReplayResult,
    UploadCancelResult,
    UploadCancel,
    UploadChunkResult,
    UploadChunk,
    UploadCompleteResult,
    UploadComplete,
    UploadCreate,
    UploadCreated,
    UploadStatus,
    Unknown,
}

public static class AssetLinkMessageTypes
{
    public const string ControlCancel = "control.cancel";
    public const string ControlResult = "control.result";
    public const string ControlRequest = "control.request";
    public const string DownloadRange = "download.range";
    public const string DownloadResult = "download.result";
    public const string Error = "error";
    public const string Event = "event";
    public const string HandshakeResponse = "handshake.response";
    public const string HandshakeRequest = "handshake.request";
    public const string EventReplayRequest = "event.replay.request";
    public const string EventReplayResult = "event.replay.result";
    public const string UploadCancelResult = "upload.cancel.result";
    public const string UploadCancel = "upload.cancel";
    public const string UploadChunkResult = "upload.chunk.result";
    public const string UploadChunk = "upload.chunk";
    public const string UploadCompleteResult = "upload.complete.result";
    public const string UploadComplete = "upload.complete";
    public const string UploadCreate = "upload.create";
    public const string UploadCreated = "upload.created";
    public const string UploadStatus = "upload.status";
}

public abstract class AssetLinkMessage(JsonObject raw)
{
    private static readonly JsonSerializerOptions SerializerOptions = new()
    {
        WriteIndented = false,
    };

    public JsonObject Raw { get; } = raw ?? throw new ArgumentNullException(nameof(raw));

    public string MessageType => GetRequiredString(Raw, "message_type");

    public string ToJson() => Raw.ToJsonString(SerializerOptions);

    protected static string GetRequiredString(JsonObject value, string name) =>
        value[name]?.GetValue<string>() ?? throw Missing(name);

    protected static string? GetOptionalString(JsonObject value, string name) =>
        value[name]?.GetValue<string>();

    protected static int GetRequiredInt32(JsonObject value, string name) =>
        value[name]?.GetValue<int>() ?? throw Missing(name);

    protected static int? GetOptionalInt32(JsonObject value, string name) =>
        value[name]?.GetValue<int>();

    protected static bool GetRequiredBoolean(JsonObject value, string name) =>
        value[name]?.GetValue<bool>() ?? throw Missing(name);

    protected static bool? GetOptionalBoolean(JsonObject value, string name) =>
        value[name]?.GetValue<bool>();

    protected static JsonObject GetRequiredObject(JsonObject value, string name) =>
        value[name] as JsonObject ?? throw Missing(name);

    protected static JsonObject? GetOptionalObject(JsonObject value, string name) =>
        value[name] as JsonObject;

    protected static IReadOnlyList<string> GetRequiredStringArray(JsonObject value, string name) =>
        GetStringArray(value, name) ?? throw Missing(name);

    protected static IReadOnlyList<string>? GetOptionalStringArray(JsonObject value, string name) =>
        GetStringArray(value, name);

    protected static IReadOnlyList<JsonObject> GetRequiredObjectArray(JsonObject value, string name) =>
        GetObjectArray(value, name) ?? throw Missing(name);

    protected static IReadOnlyList<JsonObject>? GetOptionalObjectArray(JsonObject value, string name) =>
        GetObjectArray(value, name);

    private static IReadOnlyList<string>? GetStringArray(JsonObject value, string name)
    {
        if (value[name] is null)
        {
            return null;
        }

        var array = value[name] as JsonArray ?? throw WrongType(name, "array");
        return new ReadOnlyCollection<string>(array.Select(item =>
            item?.GetValue<string>() ?? throw WrongType(name, "string array")).ToList());
    }

    private static IReadOnlyList<JsonObject>? GetObjectArray(JsonObject value, string name)
    {
        if (value[name] is null)
        {
            return null;
        }

        var array = value[name] as JsonArray ?? throw WrongType(name, "array");
        return new ReadOnlyCollection<JsonObject>(array.Select(item =>
            item as JsonObject ?? throw WrongType(name, "object array")).ToList());
    }

    private static JsonException Missing(string name) => new($"Required AssetLink field is missing: {name}");

    private static JsonException WrongType(string name, string expected) =>
        new($"AssetLink field {name} must be a {expected}.");
}

public sealed class UnknownAssetLinkMessage(JsonObject raw) : AssetLinkMessage(raw);

public static class AssetLinkCodec
{
    public static AssetLinkMessage Parse(string json)
    {
        ArgumentNullException.ThrowIfNull(json);
        var root = JsonNode.Parse(json) as JsonObject ?? throw new JsonException("AssetLink message must be a JSON object.");
        var messageType = root["message_type"]?.GetValue<string>()
            ?? throw new JsonException("AssetLink message_type must be a string.");
        return messageType switch
        {
            AssetLinkMessageTypes.ControlCancel => new ControlCancelMessage(root),
            AssetLinkMessageTypes.ControlResult => new ControlResultMessage(root),
            AssetLinkMessageTypes.ControlRequest => new ControlRequestMessage(root),
            AssetLinkMessageTypes.DownloadRange => new DownloadRangeMessage(root),
            AssetLinkMessageTypes.DownloadResult => new DownloadResultMessage(root),
            AssetLinkMessageTypes.Error => new ErrorMessage(root),
            AssetLinkMessageTypes.Event => new EventMessage(root),
            AssetLinkMessageTypes.HandshakeResponse => new HandshakeResponseMessage(root),
            AssetLinkMessageTypes.HandshakeRequest => new HandshakeRequestMessage(root),
            AssetLinkMessageTypes.EventReplayRequest => new EventReplayRequestMessage(root),
            AssetLinkMessageTypes.EventReplayResult => new EventReplayResultMessage(root),
            AssetLinkMessageTypes.UploadCancelResult => new UploadCancelResultMessage(root),
            AssetLinkMessageTypes.UploadCancel => new UploadCancelMessage(root),
            AssetLinkMessageTypes.UploadChunkResult => new UploadChunkResultMessage(root),
            AssetLinkMessageTypes.UploadChunk => new UploadChunkMessage(root),
            AssetLinkMessageTypes.UploadCompleteResult => new UploadCompleteResultMessage(root),
            AssetLinkMessageTypes.UploadComplete => new UploadCompleteMessage(root),
            AssetLinkMessageTypes.UploadCreate => new UploadCreateMessage(root),
            AssetLinkMessageTypes.UploadCreated => new UploadCreatedMessage(root),
            AssetLinkMessageTypes.UploadStatus => new UploadStatusMessage(root),
            _ => new UnknownAssetLinkMessage(root),
        };
    }

    public static AssetLinkMessageKind Classify(string messageType) => messageType switch
    {
            AssetLinkMessageTypes.ControlCancel => AssetLinkMessageKind.ControlCancel,
            AssetLinkMessageTypes.ControlResult => AssetLinkMessageKind.ControlResult,
            AssetLinkMessageTypes.ControlRequest => AssetLinkMessageKind.ControlRequest,
            AssetLinkMessageTypes.DownloadRange => AssetLinkMessageKind.DownloadRange,
            AssetLinkMessageTypes.DownloadResult => AssetLinkMessageKind.DownloadResult,
            AssetLinkMessageTypes.Error => AssetLinkMessageKind.Error,
            AssetLinkMessageTypes.Event => AssetLinkMessageKind.Event,
            AssetLinkMessageTypes.HandshakeResponse => AssetLinkMessageKind.HandshakeResponse,
            AssetLinkMessageTypes.HandshakeRequest => AssetLinkMessageKind.HandshakeRequest,
            AssetLinkMessageTypes.EventReplayRequest => AssetLinkMessageKind.EventReplayRequest,
            AssetLinkMessageTypes.EventReplayResult => AssetLinkMessageKind.EventReplayResult,
            AssetLinkMessageTypes.UploadCancelResult => AssetLinkMessageKind.UploadCancelResult,
            AssetLinkMessageTypes.UploadCancel => AssetLinkMessageKind.UploadCancel,
            AssetLinkMessageTypes.UploadChunkResult => AssetLinkMessageKind.UploadChunkResult,
            AssetLinkMessageTypes.UploadChunk => AssetLinkMessageKind.UploadChunk,
            AssetLinkMessageTypes.UploadCompleteResult => AssetLinkMessageKind.UploadCompleteResult,
            AssetLinkMessageTypes.UploadComplete => AssetLinkMessageKind.UploadComplete,
            AssetLinkMessageTypes.UploadCreate => AssetLinkMessageKind.UploadCreate,
            AssetLinkMessageTypes.UploadCreated => AssetLinkMessageKind.UploadCreated,
            AssetLinkMessageTypes.UploadStatus => AssetLinkMessageKind.UploadStatus,
        _ => AssetLinkMessageKind.Unknown,
    };
}

public static class AssetLinkUInt64
{
    private const string Maximum = "18446744073709551615";

    public static ulong Parse(string value)
    {
        ArgumentNullException.ThrowIfNull(value);
        if (value.Length == 0 || value.Length > 20 || (value.Length > 1 && value[0] == '0') ||
            value.Any(character => character is < '0' or > '9') ||
            (value.Length == 20 && string.CompareOrdinal(value, Maximum) > 0))
        {
            throw new FormatException("AssetLink uint64 must be a canonical decimal value in range.");
        }

        return ulong.Parse(value, NumberStyles.None, CultureInfo.InvariantCulture);
    }

    public static string Format(ulong value) => value.ToString(CultureInfo.InvariantCulture);
}

public sealed class ControlCancelMessage(JsonObject raw) : AssetLinkMessage(raw)
{
    public const string WireMessageType = "control.cancel";

    public string RequestId => GetRequiredString(Raw, "request_id");

    public string CancelOf => GetRequiredString(Raw, "cancel_of");
}

public sealed class ControlResultMessage(JsonObject raw) : AssetLinkMessage(raw)
{
    public const string WireMessageType = "control.result";

    public string RequestId => GetRequiredString(Raw, "request_id");

    public bool Ok => GetRequiredBoolean(Raw, "ok");

    public JsonObject Body => GetRequiredObject(Raw, "body");
}

public sealed class ControlRequestMessage(JsonObject raw) : AssetLinkMessage(raw)
{
    public const string WireMessageType = "control.request";

    public string RequestId => GetRequiredString(Raw, "request_id");

    public string Operation => GetRequiredString(Raw, "operation");

    public JsonObject Body => GetRequiredObject(Raw, "body");

    public string? IdempotencyKey => GetOptionalString(Raw, "idempotency_key");

    public int? TimeoutMs => GetOptionalInt32(Raw, "timeout_ms");

    public string? CancelOf => GetOptionalString(Raw, "cancel_of");
}

public sealed class DownloadRangeMessage(JsonObject raw) : AssetLinkMessage(raw)
{
    public const string WireMessageType = "download.range";

    public string AssetId => GetRequiredString(Raw, "asset_id");

    public string Start => GetRequiredString(Raw, "start");

    public string End => GetRequiredString(Raw, "end");
}

public sealed class DownloadResultMessage(JsonObject raw) : AssetLinkMessage(raw)
{
    public const string WireMessageType = "download.result";

    public string Length => GetRequiredString(Raw, "length");

    public string Start => GetRequiredString(Raw, "start");

    public string End => GetRequiredString(Raw, "end");

    public string ContentSha256 => GetRequiredString(Raw, "content_sha256");

    public bool Readable => GetRequiredBoolean(Raw, "readable");

    public bool Verified => GetRequiredBoolean(Raw, "verified");
}

public sealed class ErrorMessage(JsonObject raw) : AssetLinkMessage(raw)
{
    public const string WireMessageType = "error";

    public string RequestId => GetRequiredString(Raw, "request_id");

    public JsonObject Error => GetRequiredObject(Raw, "error");
}

public sealed class EventMessage(JsonObject raw) : AssetLinkMessage(raw)
{
    public const string WireMessageType = "event";

    public string EventId => GetRequiredString(Raw, "event_id");

    public string EventType => GetRequiredString(Raw, "event_type");

    public string Cursor => GetRequiredString(Raw, "cursor");

    public string Sequence => GetRequiredString(Raw, "sequence");

    public string OccurredAt => GetRequiredString(Raw, "occurred_at");

    public JsonObject Payload => GetRequiredObject(Raw, "payload");
}

public sealed class HandshakeResponseMessage(JsonObject raw) : AssetLinkMessage(raw)
{
    public const string WireMessageType = "handshake.response";

    public string SelectedVersion => GetRequiredString(Raw, "selected_version");

    public string ServerId => GetRequiredString(Raw, "server_id");

    public string ServerVersion => GetRequiredString(Raw, "server_version");

    public IReadOnlyList<string> Capabilities => GetRequiredStringArray(Raw, "capabilities");

    public string EndpointRole => GetRequiredString(Raw, "endpoint_role");

    public string? RequestId => GetOptionalString(Raw, "request_id");
}

public sealed class HandshakeRequestMessage(JsonObject raw) : AssetLinkMessage(raw)
{
    public const string WireMessageType = "handshake.request";

    public JsonObject Client => GetRequiredObject(Raw, "client");

    public IReadOnlyList<string> SupportedVersions => GetRequiredStringArray(Raw, "supported_versions");

    public IReadOnlyList<string> Capabilities => GetRequiredStringArray(Raw, "capabilities");

    public string EndpointRole => GetRequiredString(Raw, "endpoint_role");

    public string? RequestId => GetOptionalString(Raw, "request_id");
}

public sealed class EventReplayRequestMessage(JsonObject raw) : AssetLinkMessage(raw)
{
    public const string WireMessageType = "event.replay.request";

    public string AfterCursor => GetRequiredString(Raw, "after_cursor");

    public int Limit => GetRequiredInt32(Raw, "limit");

    public string RequestId => GetRequiredString(Raw, "request_id");
}

public sealed class EventReplayResultMessage(JsonObject raw) : AssetLinkMessage(raw)
{
    public const string WireMessageType = "event.replay.result";

    public IReadOnlyList<JsonObject> Events => GetRequiredObjectArray(Raw, "events");

    public string NextCursor => GetRequiredString(Raw, "next_cursor");

    public bool Gap => GetRequiredBoolean(Raw, "gap");

    public string RequestId => GetRequiredString(Raw, "request_id");
}

public sealed class UploadCancelResultMessage(JsonObject raw) : AssetLinkMessage(raw)
{
    public const string WireMessageType = "upload.cancel.result";

    public string RequestId => GetRequiredString(Raw, "request_id");

    public string TransferId => GetRequiredString(Raw, "transfer_id");

    public bool Cancelled => GetRequiredBoolean(Raw, "cancelled");
}

public sealed class UploadCancelMessage(JsonObject raw) : AssetLinkMessage(raw)
{
    public const string WireMessageType = "upload.cancel";

    public string RequestId => GetRequiredString(Raw, "request_id");

    public string TransferId => GetRequiredString(Raw, "transfer_id");
}

public sealed class UploadChunkResultMessage(JsonObject raw) : AssetLinkMessage(raw)
{
    public const string WireMessageType = "upload.chunk.result";

    public string RequestId => GetRequiredString(Raw, "request_id");

    public string TransferId => GetRequiredString(Raw, "transfer_id");

    public string Offset => GetRequiredString(Raw, "offset");

    public bool Accepted => GetRequiredBoolean(Raw, "accepted");

    public bool Duplicate => GetRequiredBoolean(Raw, "duplicate");
}

public sealed class UploadChunkMessage(JsonObject raw) : AssetLinkMessage(raw)
{
    public const string WireMessageType = "upload.chunk";

    public string RequestId => GetRequiredString(Raw, "request_id");

    public string TransferId => GetRequiredString(Raw, "transfer_id");

    public string Offset => GetRequiredString(Raw, "offset");

    public int ChunkSize => GetRequiredInt32(Raw, "chunk_size");

    public string ChunkSha256 => GetRequiredString(Raw, "chunk_sha256");
}

public sealed class UploadCompleteResultMessage(JsonObject raw) : AssetLinkMessage(raw)
{
    public const string WireMessageType = "upload.complete.result";

    public string RequestId => GetRequiredString(Raw, "request_id");

    public string TransferId => GetRequiredString(Raw, "transfer_id");

    public bool Verified => GetRequiredBoolean(Raw, "verified");

    public bool Readable => GetRequiredBoolean(Raw, "readable");

    public string VerifiedLength => GetRequiredString(Raw, "verified_length");

    public string VerifiedSha256 => GetRequiredString(Raw, "verified_sha256");
}

public sealed class UploadCompleteMessage(JsonObject raw) : AssetLinkMessage(raw)
{
    public const string WireMessageType = "upload.complete";

    public string RequestId => GetRequiredString(Raw, "request_id");

    public string TransferId => GetRequiredString(Raw, "transfer_id");

    public string ContentSha256 => GetRequiredString(Raw, "content_sha256");

    public string IdempotencyKey => GetRequiredString(Raw, "idempotency_key");
}

public sealed class UploadCreateMessage(JsonObject raw) : AssetLinkMessage(raw)
{
    public const string WireMessageType = "upload.create";

    public string RequestId => GetRequiredString(Raw, "request_id");

    public string Length => GetRequiredString(Raw, "length");

    public string ContentSha256 => GetRequiredString(Raw, "content_sha256");

    public string IdempotencyKey => GetRequiredString(Raw, "idempotency_key");
}

public sealed class UploadCreatedMessage(JsonObject raw) : AssetLinkMessage(raw)
{
    public const string WireMessageType = "upload.created";

    public string RequestId => GetRequiredString(Raw, "request_id");

    public string TransferId => GetRequiredString(Raw, "transfer_id");

    public string Length => GetRequiredString(Raw, "length");
}

public sealed class UploadStatusMessage(JsonObject raw) : AssetLinkMessage(raw)
{
    public const string WireMessageType = "upload.status";

    public string TransferId => GetRequiredString(Raw, "transfer_id");

    public string Length => GetRequiredString(Raw, "length");

    public IReadOnlyList<JsonObject> ReceivedRanges => GetRequiredObjectArray(Raw, "received_ranges");
}
