using System.Buffers.Binary;
using System.Text;
using AssetLibrary.Windows.AssetHost;

namespace AssetLibrary.Windows.Tests;

[TestClass]
public sealed class HostProtocolTests
{
    // Literal fixture from contracts/windows-shell/wire-vectors-v1.json; not generated by the implementation.
    private const string ReadyVector = "414c53310100020032000000070000000000000033221100554477668899aabbccddeeff01000000ccddeeffaabb8899776655443322110001000300448d9965935e";

    [TestMethod]
    public void IndependentLittleEndianVectorsAgree()
    {
        var request = SnapshotProtocol.EncodeRequest(HostTestSupport.Root);
        CollectionAssert.AreEqual(Convert.FromHexString("414C5331010001002000000007000000" + new string('0', 64)), request);
        Assert.AreEqual(HostTestSupport.Root, SnapshotProtocol.DecodeRequest(request));
        var response = SnapshotProtocol.DecodeResponse(Convert.FromHexString(ReadyVector), 7);
        Assert.AreEqual(Guid.Parse("00112233-4455-6677-8899-aabbccddeeff"), response.Epoch);
        Assert.AreEqual(Guid.Parse("ffeeddcc-bbaa-9988-7766-554433221100"), response.Items.Single().Node);
        Assert.AreEqual("资料库", response.Items.Single().Name);
        CollectionAssert.AreEqual(Convert.FromHexString(ReadyVector), SnapshotProtocol.EncodeResponse(7, response));
    }

    [TestMethod]
    [DataRow(0, 0)]
    [DataRow(4, 2)]
    [DataRow(6, 3)]
    [DataRow(8, 33)]
    [DataRow(12, 0)]
    public void InvalidRequestHeadersRejectBeforePayloadUse(int offset, int value)
    {
        var bytes = SnapshotProtocol.EncodeRequest(HostTestSupport.Root);
        bytes[offset] = (byte)value;
        Assert.ThrowsExactly<InvalidDataException>(() => SnapshotProtocol.DecodeRequest(bytes));
    }

    [TestMethod]
    public void RequestScopesAndTrailingBytesAreRejected()
    {
        Assert.ThrowsExactly<InvalidDataException>(() => SnapshotProtocol.EncodeRequest(new(1, Guid.NewGuid(), Guid.Empty)));
        Assert.ThrowsExactly<InvalidDataException>(() => SnapshotProtocol.DecodeRequest(new byte[47]));
        var bytes = SnapshotProtocol.EncodeRequest(HostTestSupport.Root).Concat(new byte[1]).ToArray();
        Assert.ThrowsExactly<InvalidDataException>(() => SnapshotProtocol.DecodeRequest(bytes));
    }

    [TestMethod]
    public void ResponseCorrelationBoundsAndTrailingDataAreRejected()
    {
        var bytes = Convert.FromHexString(ReadyVector);
        Assert.ThrowsExactly<InvalidDataException>(() => SnapshotProtocol.DecodeResponse(bytes, 8));
        BinaryPrimitives.WriteUInt32LittleEndian(bytes.AsSpan(36), 102);
        Assert.ThrowsExactly<InvalidDataException>(() => SnapshotProtocol.DecodeResponse(bytes, 7));
        bytes = Convert.FromHexString(ReadyVector).Concat(new byte[2]).ToArray();
        BinaryPrimitives.WriteUInt32LittleEndian(bytes.AsSpan(8), (uint)(bytes.Length - 16));
        Assert.ThrowsExactly<InvalidDataException>(() => SnapshotProtocol.DecodeResponse(bytes, 7));
        bytes = new byte[65553];
        Assert.ThrowsExactly<InvalidDataException>(() => SnapshotProtocol.DecodeResponse(bytes, 7));
    }

    [TestMethod]
    public void InvalidStatusesTokensKindsAndTextNeverBecomeEmptySuccess()
    {
        var valid = SnapshotProtocol.DecodeResponse(Convert.FromHexString(ReadyVector), 7);
        Assert.ThrowsExactly<InvalidDataException>(() => SnapshotProtocol.EncodeResponse(7, valid with { Status = SnapshotStatus.Loading }));
        Assert.ThrowsExactly<InvalidDataException>(() => SnapshotProtocol.EncodeResponse(7, valid with { Status = (SnapshotStatus)100 }));
        Assert.ThrowsExactly<InvalidDataException>(() => SnapshotProtocol.EncodeResponse(7, valid with { Epoch = Guid.Empty }));
        Assert.ThrowsExactly<InvalidDataException>(() => SnapshotProtocol.EncodeResponse(7, valid with { Items = [valid.Items[0], valid.Items[0]] }));
        foreach (var item in new[] { valid.Items[0] with { Node = Guid.Empty }, valid.Items[0] with { Kind = (SnapshotKind)0 },
            valid.Items[0] with { Name = "bad\0name" }, valid.Items[0] with { Name = "bad\u0085name" }, valid.Items[0] with { Name = new string('a', 256) } })
        { Assert.ThrowsExactly<InvalidDataException>(() => SnapshotProtocol.EncodeResponse(7, valid with { Items = [item] })); }
        Assert.ThrowsExactly<EncoderFallbackException>(() => SnapshotProtocol.ValidateName("\ud800"));
        var bytes = Convert.FromHexString(ReadyVector);
        bytes[^4] = 0; bytes[^3] = 0xD8;
        Assert.ThrowsExactly<DecoderFallbackException>(() => SnapshotProtocol.DecodeResponse(bytes, 7));
    }

    [TestMethod]
    public void MaximumPageAndSurrogatePairAreAccepted()
    {
        var entries = Enumerable.Range(0, 101).Select(index => new SnapshotItem(Guid.NewGuid(), index == 100 ? SnapshotKind.NextPage : SnapshotKind.File, new string('a', 253) + "😀")).ToArray();
        var response = new SnapshotResponse(SnapshotStatus.Ready, Guid.NewGuid(), entries);
        var bytes = SnapshotProtocol.EncodeResponse(1, response);
        Assert.IsLessThanOrEqualTo(65552, bytes.Length);
        Assert.HasCount(101, SnapshotProtocol.DecodeResponse(bytes, 1).Items);
    }

    [TestMethod]
    public void ExtraNavigationOrPhysicalItemsAreRejected()
    {
        var items = Enumerable.Range(0, 101).Select(_ => new SnapshotItem(Guid.NewGuid(), SnapshotKind.File, "file")).ToArray();
        var response = new SnapshotResponse(SnapshotStatus.Ready, Guid.NewGuid(), items);
        Assert.ThrowsExactly<InvalidDataException>(() => SnapshotProtocol.EncodeResponse(1, response));
        var navigation = new[] { items[0] with { Kind = SnapshotKind.NextPage }, items[1] with { Kind = SnapshotKind.NextPage } };
        Assert.ThrowsExactly<InvalidDataException>(() => SnapshotProtocol.EncodeResponse(1, response with { Items = navigation }));
    }
}
