// <auto-generated />
// Generated by scripts/generate_assetlink_sdks.py; contract 6b80d07c807f844de9d414272b87b8d696fe69e7fe12450f76b3e60ffb9c4e09.

export interface ControlCancel {
  readonly [key: string]: unknown;
  message_type: "control.cancel";
  request_id: string;
  cancel_of: string;
}
export interface ControlResult {
  readonly [key: string]: unknown;
  message_type: "control.result";
  request_id: string;
  ok: boolean;
  body: Record<string, unknown>;
}
export interface ControlRequest {
  readonly [key: string]: unknown;
  message_type: "control.request";
  request_id: string;
  operation: string;
  body: Record<string, unknown>;
  idempotency_key?: string;
  timeout_ms?: number;
  cancel_of?: string;
}
export interface DownloadRange {
  readonly [key: string]: unknown;
  message_type: "download.range";
  asset_id: string;
  start: string;
  end: string;
}
export interface DownloadResult {
  readonly [key: string]: unknown;
  message_type: "download.result";
  length: string;
  start: string;
  end: string;
  content_sha256: string;
  readable: boolean;
  verified: boolean;
}
export interface Error {
  readonly [key: string]: unknown;
  message_type: "error";
  request_id: string;
  error: Record<string, unknown>;
}
export interface Event {
  readonly [key: string]: unknown;
  message_type: "event";
  event_id: string;
  event_type: string;
  cursor: string;
  sequence: string;
  occurred_at: string;
  payload: Record<string, unknown>;
}
export interface HandshakeResponse {
  readonly [key: string]: unknown;
  message_type: "handshake.response";
  selected_version: string;
  server_id: string;
  server_version: string;
  capabilities: readonly string[];
  endpoint_role: string;
  request_id?: string;
}
export interface HandshakeRequest {
  readonly [key: string]: unknown;
  message_type: "handshake.request";
  client: Record<string, unknown>;
  supported_versions: readonly string[];
  capabilities: readonly string[];
  endpoint_role: string;
  request_id?: string;
}
export interface EventReplayRequest {
  readonly [key: string]: unknown;
  message_type: "event.replay.request";
  after_cursor: string;
  limit: number;
  request_id: string;
}
export interface EventReplayResult {
  readonly [key: string]: unknown;
  message_type: "event.replay.result";
  events: readonly Record<string, unknown>[];
  next_cursor: string;
  gap: boolean;
  request_id: string;
}
export interface UploadCancelResult {
  readonly [key: string]: unknown;
  message_type: "upload.cancel.result";
  request_id: string;
  transfer_id: string;
  cancelled: boolean;
}
export interface UploadCancel {
  readonly [key: string]: unknown;
  message_type: "upload.cancel";
  request_id: string;
  transfer_id: string;
}
export interface UploadChunkResult {
  readonly [key: string]: unknown;
  message_type: "upload.chunk.result";
  request_id: string;
  transfer_id: string;
  offset: string;
  accepted: boolean;
  duplicate: boolean;
}
export interface UploadChunk {
  readonly [key: string]: unknown;
  message_type: "upload.chunk";
  request_id: string;
  transfer_id: string;
  offset: string;
  chunk_size: number;
  chunk_sha256: string;
}
export interface UploadCompleteResult {
  readonly [key: string]: unknown;
  message_type: "upload.complete.result";
  request_id: string;
  transfer_id: string;
  verified: boolean;
  readable: boolean;
  verified_length: string;
  verified_sha256: string;
}
export interface UploadComplete {
  readonly [key: string]: unknown;
  message_type: "upload.complete";
  request_id: string;
  transfer_id: string;
  content_sha256: string;
  idempotency_key: string;
}
export interface UploadCreate {
  readonly [key: string]: unknown;
  message_type: "upload.create";
  request_id: string;
  length: string;
  content_sha256: string;
  idempotency_key: string;
}
export interface UploadCreated {
  readonly [key: string]: unknown;
  message_type: "upload.created";
  request_id: string;
  transfer_id: string;
  length: string;
}
export interface UploadStatus {
  readonly [key: string]: unknown;
  message_type: "upload.status";
  transfer_id: string;
  length: string;
  received_ranges: readonly Record<string, unknown>[];
}

export interface UnknownAssetLinkMessage {
  readonly [key: string]: unknown;
  readonly message_type: string;
}

export type KnownAssetLinkMessage =
  | ControlCancel
  | ControlResult
  | ControlRequest
  | DownloadRange
  | DownloadResult
  | Error
  | Event
  | HandshakeResponse
  | HandshakeRequest
  | EventReplayRequest
  | EventReplayResult
  | UploadCancelResult
  | UploadCancel
  | UploadChunkResult
  | UploadChunk
  | UploadCompleteResult
  | UploadComplete
  | UploadCreate
  | UploadCreated
  | UploadStatus;

export type AssetLinkMessage = KnownAssetLinkMessage | UnknownAssetLinkMessage;
export type AssetLinkMessageKind = KnownAssetLinkMessage["message_type"] | "unknown";

export const assetLinkMessageTypes = {
  controlcancel: "control.cancel",
  controlresult: "control.result",
  controlrequest: "control.request",
  downloadrange: "download.range",
  downloadresult: "download.result",
  error: "error",
  event: "event",
  handshakeresponse: "handshake.response",
  handshakerequest: "handshake.request",
  eventreplayrequest: "event.replay.request",
  eventreplayresult: "event.replay.result",
  uploadcancelresult: "upload.cancel.result",
  uploadcancel: "upload.cancel",
  uploadchunkresult: "upload.chunk.result",
  uploadchunk: "upload.chunk",
  uploadcompleteresult: "upload.complete.result",
  uploadcomplete: "upload.complete",
  uploadcreate: "upload.create",
  uploadcreated: "upload.created",
  uploadstatus: "upload.status",
} as const;

export function classifyAssetLinkMessage(messageType: string): AssetLinkMessageKind {
  switch (messageType) {
    case "control.cancel":
    case "control.result":
    case "control.request":
    case "download.range":
    case "download.result":
    case "error":
    case "event":
    case "handshake.response":
    case "handshake.request":
    case "event.replay.request":
    case "event.replay.result":
    case "upload.cancel.result":
    case "upload.cancel":
    case "upload.chunk.result":
    case "upload.chunk":
    case "upload.complete.result":
    case "upload.complete":
    case "upload.create":
    case "upload.created":
    case "upload.status":
      return messageType;
    default:
      return "unknown";
  }
}

export function parseAssetLinkMessage(json: string): AssetLinkMessage {
  const value: unknown = JSON.parse(json);
  if (!isRecord(value) || typeof value.message_type !== "string") {
    throw new TypeError("AssetLink message must be an object with a string message_type.");
  }
  return value as AssetLinkMessage;
}

export function encodeAssetLinkMessage(message: AssetLinkMessage): string {
  return JSON.stringify(message);
}

const maximumUint64 = BigInt("18446744073709551615");
const canonicalUint64 = /^(0|[1-9][0-9]*)$/;

export function parseAssetLinkUint64(value: string): bigint {
  if (!canonicalUint64.test(value) || value.length > 20) {
    throw new RangeError("AssetLink uint64 must be a canonical decimal value in range.");
  }
  const parsed = BigInt(value);
  if (parsed > maximumUint64) {
    throw new RangeError("AssetLink uint64 must be a canonical decimal value in range.");
  }
  return parsed;
}

export function formatAssetLinkUint64(value: bigint): string {
  if (value < 0n || value > maximumUint64) {
    throw new RangeError("AssetLink uint64 is outside the unsigned 64-bit range.");
  }
  return value.toString(10);
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
