#!/usr/bin/env python3
"""Export native resources from the existing authoritative Web semantic colors."""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCES = {
    "light": "apps/web/src/styles/base.css",
    "dark": "apps/web/src/styles/responsive.css",
}
KEYS = {
    "ink", "muted", "line", "surface", "surface-strong", "accent",
    "accent-soft", "on-accent", "danger", "positive", "folder", "focus",
}
OUTPUT = ROOT / "packages/ui/workspace-theme.json"
CPP_OUTPUT = ROOT / "apps/windows-shell/generated/WorkspaceTheme.generated.h"


def render() -> str:
    themes = {}
    for theme, source in SOURCES.items():
        css = (ROOT / source).read_text(encoding="utf-8")
        colors = dict(re.findall(r"--([a-z-]+):\s*(#[0-9a-fA-F]{6});", css))
        if set(colors) != KEYS:
            raise ValueError(f"Unexpected semantic token set in {source}")
        themes[theme] = colors
    return json.dumps({
        "generated_by": "scripts/export_native_theme.py; do not edit",
        "sources": SOURCES,
        "themes": themes,
    }, ensure_ascii=False, indent=2) + "\n"


def render_cpp(theme_json: str) -> str:
    themes = json.loads(theme_json)["themes"]
    names = sorted(KEYS)
    lines = ["// Generated by scripts/export_native_theme.py; do not edit.",
             "#pragma once", "#include <windows.h>", "namespace workspace_theme {", "struct Colors {"]
    lines += [f"    COLORREF {name.replace('-', '_')};" for name in names]
    lines.append("};")
    for theme in ("light", "dark"):
        values = []
        for name in names:
            value = int(themes[theme][name][1:], 16)
            colorref = ((value >> 16) & 255) | (value & 0xFF00) | ((value & 255) << 16)
            values.append(f"0x{colorref:06X}u")
        lines.append(f"inline constexpr Colors {theme}{{" + ", ".join(values) + "};")
    return "\n".join([*lines, "} // namespace workspace_theme", ""])


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    outputs = {OUTPUT: expected, CPP_OUTPUT: render_cpp(expected)}
    if args.check:
        if any(not path.exists() or path.read_text(encoding="utf-8") != content for path, content in outputs.items()):
            print("Native theme differs from Web semantic colors; run scripts/export_native_theme.py")
            return 1
    else:
        for path, content in outputs.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    print("Native semantic theme is current.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
