#!/usr/bin/env python3
"""Generate deterministic AssetLink wire SDKs from the canonical JSON schemas."""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
CONTRACT_ROOT = ROOT / "contracts" / "assetlink"
SDK_ROOT = ROOT / "packages" / "sdk" / "assetlink"
GENERATOR_VERSION = 1
UINT64_MAX = "18446744073709551615"
GENERATED_MARKERS = ("<auto-generated", "generated by scripts/generate_assetlink_sdks.py")
IGNORED_GENERATED_DIRECTORIES = {".gradle", "bin", "build", "dist", "node_modules", "obj"}
EXPECTED_COMMON_KINDS = {
    "uint64_decimal": "string",
    "opaque_id": "string",
    "request_id": "string",
    "cursor": "string",
    "version": "string",
    "version_list": "string_array",
    "capabilities": "string_array",
    "endpoint_role": "string",
    "client": "object",
    "server_id": "string",
    "sha256": "string",
    "byte_range": "object",
}


@dataclass(frozen=True)
class MessageSchema:
    schema_file: str
    message_type: str
    document: dict[str, Any]

    @property
    def class_name(self) -> str:
        name = "".join(part.capitalize() for part in re.split(r"[^A-Za-z0-9]+", self.message_type))
        return f"{name}Message"


def contract_digest(root: Path) -> str:
    digest = hashlib.sha256()
    for path in sorted((item for item in root.rglob("*") if item.is_file()), key=lambda item: item.as_posix()):
        relative = path.relative_to(root).as_posix().encode("utf-8")
        content = path.read_bytes().replace(b"\r\n", b"\n").replace(b"\r", b"\n")
        digest.update(len(relative).to_bytes(4, "big"))
        digest.update(relative)
        digest.update(len(content).to_bytes(8, "big"))
        digest.update(content)
    return digest.hexdigest()


def infer_common_kind(definitions: dict[str, Any], name: str, visiting: set[str] | None = None) -> str:
    if name not in definitions or not isinstance(definitions[name], dict):
        raise ValueError(f"common schema definition is missing or invalid: {name}")
    trail = set() if visiting is None else set(visiting)
    if name in trail:
        raise ValueError(f"common schema definition cycle is unsupported: {name}")
    trail.add(name)
    specification = definitions[name]
    reference = specification.get("$ref")
    if isinstance(reference, str):
        prefix = "#/$defs/"
        if not reference.startswith(prefix):
            raise ValueError(f"unsupported common schema reference: {reference}")
        return infer_common_kind(definitions, reference.removeprefix(prefix), trail)
    kind = specification.get("type")
    if kind == "array":
        item = specification.get("items", {})
        item_reference = item.get("$ref") if isinstance(item, dict) else None
        if isinstance(item_reference, str) and item_reference.startswith("#/$defs/"):
            item_kind = infer_common_kind(definitions, item_reference.rsplit("/", 1)[-1], trail)
        else:
            item_kind = item.get("type") if isinstance(item, dict) else None
        return f"{item_kind}_array"
    if kind in {"string", "object"}:
        return kind
    raise ValueError(f"unsupported common schema definition shape: {name}")


def validate_common_schema(document: dict[str, Any]) -> None:
    definitions = document.get("$defs")
    if not isinstance(definitions, dict) or set(definitions) != set(EXPECTED_COMMON_KINDS):
        raise ValueError("common schema definitions differ from the supported AssetLink v1 set")
    actual = {name: infer_common_kind(definitions, name) for name in definitions}
    if actual != EXPECTED_COMMON_KINDS:
        raise ValueError(f"common schema definition kinds are unsupported: {actual}")
    uint64 = definitions["uint64_decimal"]
    if uint64.get("format") != "uint64-decimal" or uint64.get("maxLength") != 20:
        raise ValueError("uint64_decimal must retain the checked 20-digit wire format")


def iter_references(value: Any):
    if isinstance(value, dict):
        for key, child in value.items():
            if key == "$ref" and isinstance(child, str):
                yield child
            else:
                yield from iter_references(child)
    elif isinstance(value, list):
        for child in value:
            yield from iter_references(child)


def load_messages() -> list[MessageSchema]:
    messages: list[MessageSchema] = []
    schema_names = {path.name for path in CONTRACT_ROOT.glob("*.schema.json")}
    common_path = CONTRACT_ROOT / "common.schema.json"
    common = json.loads(common_path.read_text(encoding="utf-8"))
    validate_common_schema(common)
    for path in sorted(CONTRACT_ROOT.glob("*.schema.json")):
        document = json.loads(path.read_text(encoding="utf-8"))
        if path.name == "common.schema.json":
            continue
        message_type = document.get("properties", {}).get("message_type", {}).get("const")
        if not isinstance(message_type, str):
            raise ValueError(f"{path.name} lacks a string message_type const")
        if document.get("type") != "object" or document.get("additionalProperties") is not True:
            raise ValueError(f"{path.name} must be an open object envelope")
        for reference in iter_references(document):
            external_name = reference.partition("#")[0]
            if external_name and external_name not in schema_names:
                raise ValueError(f"{path.name} has an unresolved schema reference: {reference}")
        messages.append(MessageSchema(path.name, message_type, document))
    if len(messages) != 20:
        raise ValueError(f"expected 20 AssetLink envelopes, found {len(messages)}")
    return messages


def snake_to_pascal(value: str) -> str:
    return "".join(part.capitalize() for part in value.split("_"))


def snake_to_camel(value: str) -> str:
    pascal = snake_to_pascal(value)
    return pascal[:1].lower() + pascal[1:]


def ref_name(specification: dict[str, Any]) -> str | None:
    reference = specification.get("$ref")
    if not isinstance(reference, str):
        return None
    return reference.rsplit("/", 1)[-1]


def array_item_kind(specification: dict[str, Any]) -> str:
    item = specification.get("items", {})
    reference = ref_name(item)
    if reference in {"version", "opaque_id"}:
        return "string"
    if reference or item.get("type") == "object":
        return "object"
    return str(item.get("type", "unknown"))


def field_kind(specification: dict[str, Any]) -> str:
    reference = ref_name(specification)
    if reference in {"uint64_decimal", "opaque_id", "request_id", "cursor", "version", "server_id", "sha256", "endpoint_role"}:
        return "string"
    if reference in {"version_list", "capabilities"}:
        return "string_array"
    if reference in {"client", "byte_range"}:
        return "object"
    if reference == "event.schema.json":
        return "object"
    if reference:
        raise ValueError(f"unsupported AssetLink schema reference: {specification['$ref']}")
    if "const" in specification:
        value = specification["const"]
        if isinstance(value, bool):
            return "boolean"
        if isinstance(value, str):
            return "string"
    kind = specification.get("type")
    if kind == "array":
        return f"{array_item_kind(specification)}_array"
    return str(kind)


def shape_document(messages: list[MessageSchema], digest: str) -> dict[str, Any]:
    return {
        "generator_version": GENERATOR_VERSION,
        "contract_sha256": digest,
        "messages": [
            {
                "schema_file": message.schema_file,
                "message_type": message.message_type,
                "required": list(message.document.get("required", [])),
                "properties": {
                    name: {
                        "required": name in message.document.get("required", []),
                        "kind": field_kind(specification),
                        "schema": specification,
                    }
                    for name, specification in message.document.get("properties", {}).items()
                },
            }
            for message in messages
        ],
    }


def json_bytes(value: Any) -> bytes:
    return (json.dumps(value, ensure_ascii=False, indent=2) + "\n").encode("utf-8")


def csharp_type(kind: str, required: bool) -> str:
    base = {
        "string": "string",
        "integer": "int",
        "boolean": "bool",
        "object": "JsonObject",
        "string_array": "IReadOnlyList<string>",
        "object_array": "IReadOnlyList<JsonObject>",
    }[kind]
    return base if required else f"{base}?"


def csharp_getter(kind: str, required: bool, wire_name: str) -> str:
    suffix = "Required" if required else "Optional"
    method = {
        "string": f"Get{suffix}String",
        "integer": f"Get{suffix}Int32",
        "boolean": f"Get{suffix}Boolean",
        "object": f"Get{suffix}Object",
        "string_array": f"Get{suffix}StringArray",
        "object_array": f"Get{suffix}ObjectArray",
    }[kind]
    return f'{method}(Raw, "{wire_name}")'


def render_csharp(messages: list[MessageSchema], digest: str) -> str:
    enum_values = "\n".join(f"    {message.class_name.removesuffix('Message')}," for message in messages)
    constants = "\n".join(
        f'    public const string {message.class_name.removesuffix("Message")} = "{message.message_type}";'
        for message in messages
    )
    switch_arms = "\n".join(
        f'            AssetLinkMessageTypes.{message.class_name.removesuffix("Message")} => new {message.class_name}(root),'
        for message in messages
    )
    classifier_arms = "\n".join(
        f'            AssetLinkMessageTypes.{message.class_name.removesuffix("Message")} => AssetLinkMessageKind.{message.class_name.removesuffix("Message")},'
        for message in messages
    )
    classes: list[str] = []
    for message in messages:
        properties: list[str] = []
        for name, specification in message.document["properties"].items():
            if name == "message_type":
                continue
            required = name in message.document.get("required", [])
            kind = field_kind(specification)
            property_type = csharp_type(kind, required)
            getter = csharp_getter(kind, required, name)
            properties.append(f"    public {property_type} {snake_to_pascal(name)} => {getter};")
        property_block = "\n\n".join(properties)
        classes.append(
            f"public sealed class {message.class_name}(JsonObject raw) : AssetLinkMessage(raw)\n"
            "{\n"
            f'    public const string WireMessageType = "{message.message_type}";\n\n'
            f"{property_block}\n"
            "}"
        )
    class_block = "\n\n".join(classes)
    return f'''// <auto-generated />
// Generated by scripts/generate_assetlink_sdks.py; contract {digest}.
#nullable enable
using System.Collections.ObjectModel;
using System.Globalization;
using System.Text.Json;
using System.Text.Json.Nodes;

namespace AssetLibrary.AssetLink;

public enum AssetLinkMessageKind
{{
{enum_values}
    Unknown,
}}

public static class AssetLinkMessageTypes
{{
{constants}
}}

public abstract class AssetLinkMessage(JsonObject raw)
{{
    private static readonly JsonSerializerOptions SerializerOptions = new()
    {{
        WriteIndented = false,
    }};

    public JsonObject Raw {{ get; }} = raw ?? throw new ArgumentNullException(nameof(raw));

    public string MessageType => GetRequiredString(Raw, "message_type");

    public string ToJson() => Raw.ToJsonString(SerializerOptions);

    protected static string GetRequiredString(JsonObject value, string name) =>
        value[name]?.GetValue<string>() ?? throw Missing(name);

    protected static string? GetOptionalString(JsonObject value, string name) =>
        value[name]?.GetValue<string>();

    protected static int GetRequiredInt32(JsonObject value, string name) =>
        value[name]?.GetValue<int>() ?? throw Missing(name);

    protected static int? GetOptionalInt32(JsonObject value, string name) =>
        value[name]?.GetValue<int>();

    protected static bool GetRequiredBoolean(JsonObject value, string name) =>
        value[name]?.GetValue<bool>() ?? throw Missing(name);

    protected static bool? GetOptionalBoolean(JsonObject value, string name) =>
        value[name]?.GetValue<bool>();

    protected static JsonObject GetRequiredObject(JsonObject value, string name) =>
        value[name] as JsonObject ?? throw Missing(name);

    protected static JsonObject? GetOptionalObject(JsonObject value, string name) =>
        value[name] as JsonObject;

    protected static IReadOnlyList<string> GetRequiredStringArray(JsonObject value, string name) =>
        GetStringArray(value, name) ?? throw Missing(name);

    protected static IReadOnlyList<string>? GetOptionalStringArray(JsonObject value, string name) =>
        GetStringArray(value, name);

    protected static IReadOnlyList<JsonObject> GetRequiredObjectArray(JsonObject value, string name) =>
        GetObjectArray(value, name) ?? throw Missing(name);

    protected static IReadOnlyList<JsonObject>? GetOptionalObjectArray(JsonObject value, string name) =>
        GetObjectArray(value, name);

    private static IReadOnlyList<string>? GetStringArray(JsonObject value, string name)
    {{
        if (value[name] is null)
        {{
            return null;
        }}

        var array = value[name] as JsonArray ?? throw WrongType(name, "array");
        return new ReadOnlyCollection<string>(array.Select(item =>
            item?.GetValue<string>() ?? throw WrongType(name, "string array")).ToList());
    }}

    private static IReadOnlyList<JsonObject>? GetObjectArray(JsonObject value, string name)
    {{
        if (value[name] is null)
        {{
            return null;
        }}

        var array = value[name] as JsonArray ?? throw WrongType(name, "array");
        return new ReadOnlyCollection<JsonObject>(array.Select(item =>
            item as JsonObject ?? throw WrongType(name, "object array")).ToList());
    }}

    private static JsonException Missing(string name) => new($"Required AssetLink field is missing: {{name}}");

    private static JsonException WrongType(string name, string expected) =>
        new($"AssetLink field {{name}} must be a {{expected}}.");
}}

public sealed class UnknownAssetLinkMessage(JsonObject raw) : AssetLinkMessage(raw);

public static class AssetLinkCodec
{{
    public static AssetLinkMessage Parse(string json)
    {{
        ArgumentNullException.ThrowIfNull(json);
        var root = JsonNode.Parse(json) as JsonObject ?? throw new JsonException("AssetLink message must be a JSON object.");
        var messageType = root["message_type"]?.GetValue<string>()
            ?? throw new JsonException("AssetLink message_type must be a string.");
        return messageType switch
        {{
{switch_arms}
            _ => new UnknownAssetLinkMessage(root),
        }};
    }}

    public static AssetLinkMessageKind Classify(string messageType) => messageType switch
    {{
{classifier_arms}
        _ => AssetLinkMessageKind.Unknown,
    }};
}}

public static class AssetLinkUInt64
{{
    private const string Maximum = "{UINT64_MAX}";

    public static ulong Parse(string value)
    {{
        ArgumentNullException.ThrowIfNull(value);
        if (value.Length == 0 || value.Length > 20 || (value.Length > 1 && value[0] == '0') ||
            value.Any(character => character is < '0' or > '9') ||
            (value.Length == 20 && string.CompareOrdinal(value, Maximum) > 0))
        {{
            throw new FormatException("AssetLink uint64 must be a canonical decimal value in range.");
        }}

        return ulong.Parse(value, NumberStyles.None, CultureInfo.InvariantCulture);
    }}

    public static string Format(ulong value) => value.ToString(CultureInfo.InvariantCulture);
}}

{class_block}
'''


def typescript_type(specification: dict[str, Any]) -> str:
    kind = field_kind(specification)
    return {
        "string": "string",
        "integer": "number",
        "boolean": "boolean",
        "object": "Record<string, unknown>",
        "string_array": "readonly string[]",
        "object_array": "readonly Record<string, unknown>[]",
    }[kind]


def render_typescript(messages: list[MessageSchema], digest: str) -> str:
    interfaces: list[str] = []
    for message in messages:
        fields = []
        required = set(message.document.get("required", []))
        for name, specification in message.document["properties"].items():
            marker = "" if name in required else "?"
            field_type = f'"{message.message_type}"' if name == "message_type" else typescript_type(specification)
            fields.append(f"  {name}{marker}: {field_type};")
        interfaces.append(
            f"export interface {message.class_name.removesuffix('Message')} {{\n"
            "  readonly [key: string]: unknown;\n"
            + "\n".join(fields)
            + "\n}"
        )
    union = "\n  | ".join(message.class_name.removesuffix("Message") for message in messages)
    entries = "\n".join(
        f'  {snake_to_camel(message.class_name.removesuffix("Message"))}: "{message.message_type}",'
        for message in messages
    )
    cases = "\n".join(f'    case "{message.message_type}":' for message in messages)
    return f'''// <auto-generated />
// Generated by scripts/generate_assetlink_sdks.py; contract {digest}.

{chr(10).join(interfaces)}

export interface UnknownAssetLinkMessage {{
  readonly [key: string]: unknown;
  readonly message_type: string;
}}

export type KnownAssetLinkMessage =
  | {union};

export type AssetLinkMessage = KnownAssetLinkMessage | UnknownAssetLinkMessage;
export type AssetLinkMessageKind = KnownAssetLinkMessage["message_type"] | "unknown";

export const assetLinkMessageTypes = {{
{entries}
}} as const;

export function classifyAssetLinkMessage(messageType: string): AssetLinkMessageKind {{
  switch (messageType) {{
{cases}
      return messageType;
    default:
      return "unknown";
  }}
}}

export function parseAssetLinkMessage(json: string): AssetLinkMessage {{
  const value: unknown = JSON.parse(json);
  if (!isRecord(value) || typeof value.message_type !== "string") {{
    throw new TypeError("AssetLink message must be an object with a string message_type.");
  }}
  return value as AssetLinkMessage;
}}

export function encodeAssetLinkMessage(message: AssetLinkMessage): string {{
  return JSON.stringify(message);
}}

const maximumUint64 = BigInt("{UINT64_MAX}");
const canonicalUint64 = /^(0|[1-9][0-9]*)$/;

export function parseAssetLinkUint64(value: string): bigint {{
  if (!canonicalUint64.test(value) || value.length > 20) {{
    throw new RangeError("AssetLink uint64 must be a canonical decimal value in range.");
  }}
  const parsed = BigInt(value);
  if (parsed > maximumUint64) {{
    throw new RangeError("AssetLink uint64 must be a canonical decimal value in range.");
  }}
  return parsed;
}}

export function formatAssetLinkUint64(value: bigint): string {{
  if (value < 0n || value > maximumUint64) {{
    throw new RangeError("AssetLink uint64 is outside the unsigned 64-bit range.");
  }}
  return value.toString(10);
}}

function isRecord(value: unknown): value is Record<string, unknown> {{
  return typeof value === "object" && value !== null && !Array.isArray(value);
}}
'''


def kotlin_type(kind: str, required: bool) -> str:
    base = {
        "string": "String",
        "integer": "Int",
        "boolean": "Boolean",
        "object": "JsonObject",
        "string_array": "List<String>",
        "object_array": "List<JsonObject>",
    }[kind]
    return base if required else f"{base}?"


def kotlin_getter(kind: str, required: bool, wire_name: str) -> str:
    suffix = "Required" if required else "Optional"
    stem = {
        "string": "String",
        "integer": "Int",
        "boolean": "Boolean",
        "object": "Object",
        "string_array": "StringList",
        "object_array": "ObjectList",
    }[kind]
    return f'raw.get{suffix}{stem}("{wire_name}")'


def render_kotlin(messages: list[MessageSchema], digest: str) -> str:
    enum_values = "\n".join(
        f"    {re.sub(r'(?<!^)(?=[A-Z])', '_', message.class_name.removesuffix('Message')).upper()},"
        for message in messages
    )
    type_constants = "\n".join(
        f'    public const val {re.sub(r"(?<!^)(?=[A-Z])", "_", message.class_name.removesuffix("Message")).upper()}: String = "{message.message_type}"'
        for message in messages
    )
    parse_arms = "\n".join(
        f'        "{message.message_type}" -> {message.class_name}(root)'
        for message in messages
    )
    classify_arms = "\n".join(
        f'        "{message.message_type}" -> AssetLinkMessageKind.{re.sub(r"(?<!^)(?=[A-Z])", "_", message.class_name.removesuffix("Message")).upper()}'
        for message in messages
    )
    classes: list[str] = []
    for message in messages:
        properties: list[str] = []
        for name, specification in message.document["properties"].items():
            if name == "message_type":
                continue
            required = name in message.document.get("required", [])
            kind = field_kind(specification)
            property_type = kotlin_type(kind, required)
            getter = kotlin_getter(kind, required, name)
            properties.append(f"    public val {snake_to_camel(name)}: {property_type} get() = {getter}")
        classes.append(
            f"public class {message.class_name}(raw: JsonObject) : AssetLinkMessage(raw) {{\n"
            f'    public companion object {{ public const val WIRE_MESSAGE_TYPE: String = "{message.message_type}" }}\n\n'
            + "\n\n".join(properties)
            + "\n}"
        )
    return f'''// <auto-generated />
// Generated by scripts/generate_assetlink_sdks.py; contract {digest}.
@file:Suppress("MagicNumber", "TooManyFunctions")

package app.assetlibrary.assetlink

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.boolean
import kotlinx.serialization.json.int
import kotlinx.serialization.json.jsonPrimitive

public enum class AssetLinkMessageKind {{
{enum_values}
    UNKNOWN,
}}

public object AssetLinkMessageTypes {{
{type_constants}
}}

public abstract class AssetLinkMessage(public val raw: JsonObject) {{
    public val messageType: String get() = raw.getRequiredString("message_type")

    public fun encode(): String = raw.toString()
}}

public class UnknownAssetLinkMessage(raw: JsonObject) : AssetLinkMessage(raw)

public object AssetLinkCodec {{
    public fun parse(input: String): AssetLinkMessage {{
        val root = Json.parseToJsonElement(input) as? JsonObject
            ?: throw IllegalArgumentException("AssetLink message must be a JSON object.")
        return when (root.getRequiredString("message_type")) {{
{parse_arms}
            else -> UnknownAssetLinkMessage(root)
        }}
    }}

    public fun classify(messageType: String): AssetLinkMessageKind = when (messageType) {{
{classify_arms}
        else -> AssetLinkMessageKind.UNKNOWN
    }}
}}

public object AssetLinkUInt64 {{
    private const val MAXIMUM: String = "{UINT64_MAX}"
    private val canonical = Regex("^(0|[1-9][0-9]*)$")

    public fun parse(value: String): ULong {{
        require(value.length <= 20 && canonical.matches(value)) {{
            "AssetLink uint64 must be a canonical decimal value in range."
        }}
        require(value.length < 20 || value <= MAXIMUM) {{
            "AssetLink uint64 must be a canonical decimal value in range."
        }}
        return value.toULong()
    }}

    public fun format(value: ULong): String = value.toString()
}}

private fun JsonObject.getRequiredPrimitive(name: String): JsonPrimitive =
    this[name] as? JsonPrimitive ?: throw IllegalArgumentException("Required AssetLink field is missing: $name")

private fun JsonObject.getOptionalPrimitive(name: String): JsonPrimitive? {{
    val value = this[name] ?: return null
    return value as? JsonPrimitive ?: throw IllegalArgumentException("AssetLink field $name must be a primitive.")
}}

private fun JsonPrimitive.requireString(name: String): String {{
    require(isString) {{ "AssetLink field $name must be a string." }}
    return content
}}

private fun JsonPrimitive.requireNonString(name: String): JsonPrimitive {{
    require(!isString) {{ "AssetLink field $name must not be a string." }}
    return this
}}

private fun JsonObject.getRequiredString(name: String): String = getRequiredPrimitive(name).requireString(name)

private fun JsonObject.getOptionalString(name: String): String? = getOptionalPrimitive(name)?.requireString(name)

private fun JsonObject.getRequiredInt(name: String): Int = getRequiredPrimitive(name).requireNonString(name).int

private fun JsonObject.getOptionalInt(name: String): Int? = getOptionalPrimitive(name)?.requireNonString(name)?.int

private fun JsonObject.getRequiredBoolean(name: String): Boolean =
    getRequiredPrimitive(name).requireNonString(name).boolean

private fun JsonObject.getOptionalBoolean(name: String): Boolean? =
    getOptionalPrimitive(name)?.requireNonString(name)?.boolean

private fun JsonObject.getRequiredObject(name: String): JsonObject =
    this[name] as? JsonObject ?: throw IllegalArgumentException("AssetLink field $name must be an object.")

private fun JsonObject.getOptionalObject(name: String): JsonObject? {{
    val value = this[name] ?: return null
    return value as? JsonObject ?: throw IllegalArgumentException("AssetLink field $name must be an object.")
}}

private fun JsonObject.getRequiredStringList(name: String): List<String> =
    (this[name] as? JsonArray)?.map {{ it.jsonPrimitive.requireString(name) }}
        ?: throw IllegalArgumentException("AssetLink field $name must be a string array.")

private fun JsonObject.getOptionalStringList(name: String): List<String>? {{
    val value = this[name] ?: return null
    return (value as? JsonArray)?.map {{ it.jsonPrimitive.requireString(name) }}
        ?: throw IllegalArgumentException("AssetLink field $name must be a string array.")
}}

private fun JsonObject.getRequiredObjectList(name: String): List<JsonObject> =
    (this[name] as? JsonArray)?.map {{ it as JsonObject }}
        ?: throw IllegalArgumentException("AssetLink field $name must be an object array.")

private fun JsonObject.getOptionalObjectList(name: String): List<JsonObject>? {{
    val value = this[name] ?: return null
    return (value as? JsonArray)?.map {{
        it as? JsonObject ?: throw IllegalArgumentException("AssetLink field $name must be an object array.")
    }} ?: throw IllegalArgumentException("AssetLink field $name must be an object array.")
}}

{chr(10).join(chr(10) + item for item in classes)}
'''


def generated_outputs() -> dict[Path, bytes]:
    messages = load_messages()
    digest = contract_digest(CONTRACT_ROOT)
    shape = shape_document(messages, digest)
    stamp = f"{digest}\n".encode("ascii")
    outputs: dict[Path, bytes] = {
        SDK_ROOT / "dotnet" / ".contract-source.sha256": stamp,
        SDK_ROOT / "dotnet" / "AssetLink.Generated.cs": render_csharp(messages, digest).encode("utf-8"),
        SDK_ROOT / "typescript" / ".contract-source.sha256": stamp,
        SDK_ROOT / "typescript" / "src" / "generated.ts": render_typescript(messages, digest).encode("utf-8"),
        SDK_ROOT / "kotlin" / ".contract-source.sha256": stamp,
        SDK_ROOT / "kotlin" / "src" / "main" / "kotlin" / "app" / "assetlibrary" / "assetlink" / "AssetLink.Generated.kt": render_kotlin(messages, digest).encode("utf-8"),
    }
    hashes = {
        path.relative_to(SDK_ROOT).as_posix(): hashlib.sha256(content).hexdigest()
        for path, content in sorted(outputs.items(), key=lambda item: item[0].as_posix())
    }
    manifest = {
        "generator": "scripts/generate_assetlink_sdks.py",
        "generator_version": GENERATOR_VERSION,
        "contract_root": "contracts/assetlink",
        "contract_sha256": digest,
        "schema_count": len(messages) + 1,
        "message_count": len(messages),
        "messages": shape["messages"],
        "generated_files": hashes,
    }
    outputs[SDK_ROOT / "generation-manifest.json"] = json_bytes(manifest)
    return outputs


def unexpected_generated_files(expected: set[Path]) -> list[Path]:
    unexpected: list[Path] = []
    for target in (SDK_ROOT / "dotnet", SDK_ROOT / "typescript", SDK_ROOT / "kotlin"):
        if not target.exists():
            continue
        for path in target.rglob("*"):
            if not path.is_file() or path in expected:
                continue
            if any(part.lower() in IGNORED_GENERATED_DIRECTORIES for part in path.relative_to(target).parts):
                continue
            try:
                prefix = path.read_text(encoding="utf-8")[:512].lower()
            except (OSError, UnicodeError):
                continue
            if any(marker in prefix for marker in GENERATED_MARKERS):
                unexpected.append(path)
    return sorted(unexpected)


def display_path(path: Path) -> str:
    try:
        return path.relative_to(ROOT).as_posix()
    except ValueError:
        return str(path)


def check(outputs: dict[Path, bytes]) -> int:
    errors: list[str] = []
    for path, expected in outputs.items():
        if not path.is_file():
            errors.append(f"missing generated file: {display_path(path)}")
        elif path.read_bytes() != expected:
            errors.append(f"stale or hand-edited generated file: {display_path(path)}")
    for path in unexpected_generated_files(set(outputs)):
        errors.append(f"unexpected generated file: {display_path(path)}")
    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1
    print(f"AssetLink SDK generation is current ({len(outputs)} generated files).")
    return 0


def write(outputs: dict[Path, bytes]) -> None:
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)
    try:
        contract_label = CONTRACT_ROOT.relative_to(ROOT).as_posix()
    except ValueError:
        contract_label = str(CONTRACT_ROOT)
    print(f"Generated {len(outputs)} AssetLink SDK files from {contract_label}.")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if generated output differs without writing files.")
    args = parser.parse_args()
    try:
        outputs = generated_outputs()
    except (OSError, UnicodeError, ValueError, json.JSONDecodeError) as exc:
        print(f"ERROR: cannot generate AssetLink SDKs: {exc}", file=sys.stderr)
        return 2
    if args.check:
        return check(outputs)
    write(outputs)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
