#!/usr/bin/env python3
"""Fail closed on duplicated C# blocks and likely sensitive logging."""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOTS = (
    "services/core-server",
    "services/worker-supervisor",
    "tests/dotnet",
    "apps/windows-client",
    "tests/windows-client",
)
IGNORED_DIRECTORIES = {"bin", "obj"}
TOKEN_RE = re.compile(
    r'@?"(?:""|\\.|[^"\\])*"|\'(?:\\.|[^\'\\])*\'|'
    r"[A-Za-z_][A-Za-z0-9_]*|\d+(?:\.\d+)?|=>|==|!=|<=|>=|&&|\|\||\?\?|[{}()[\];,.?:+*/%<>=!-]"
)
LOG_CALL_RE = re.compile(
    r"\b(?:Console\.(?:Write|WriteLine)|[A-Za-z_][A-Za-z0-9_]*Logger\.(?:Log[A-Za-z]*|BeginScope)|"
    r"logger\.(?:Log[A-Za-z]*|BeginScope))\s*\(",
    re.IGNORECASE,
)
SENSITIVE_RE = re.compile(
    r"password|passwd|secret|token|authorization|cookie|credential|api[_-]?key",
    re.IGNORECASE,
)


def source_files(root: Path) -> list[Path]:
    files: list[Path] = []
    for source_root in SOURCE_ROOTS:
        base = root / source_root
        if not base.exists():
            continue
        for path in base.rglob("*.cs"):
            if any(part.lower() in IGNORED_DIRECTORIES for part in path.parts):
                continue
            if path.name.lower().endswith((".g.cs", ".designer.cs")):
                continue
            text = path.read_text(encoding="utf-8")
            if "<auto-generated" not in text[:512].lower():
                files.append(path)
    return sorted(files)


def code_without_comment_lines(text: str) -> str:
    without_block_comments = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
    return "\n".join(
        line for line in without_block_comments.splitlines()
        if not line.lstrip().startswith(("//", "///"))
    )


def normalized_tokens(text: str) -> list[str]:
    tokens = TOKEN_RE.findall(code_without_comment_lines(text))
    return ["STRING" if token.startswith(('"', '@"', "'")) else token for token in tokens]


def duplicate_blocks(files: list[Path], root: Path, window_size: int = 60) -> list[str]:
    occurrences: dict[tuple[str, ...], tuple[Path, int]] = {}
    duplicate_pairs: dict[tuple[str, str], tuple[int, int]] = {}
    for path in files:
        tokens = normalized_tokens(path.read_text(encoding="utf-8"))
        if len(tokens) < window_size:
            continue
        for index in range(len(tokens) - window_size + 1):
            window = tuple(tokens[index:index + window_size])
            previous = occurrences.get(window)
            if previous is None:
                occurrences[window] = (path, index)
                continue
            previous_path, previous_index = previous
            if previous_path == path:
                continue
            left = previous_path.relative_to(root).as_posix()
            right = path.relative_to(root).as_posix()
            key = tuple(sorted((left, right)))
            duplicate_pairs.setdefault(key, (previous_index, index))
    return [
        f"duplicated C# token block ({window_size} tokens): {left} <-> {right}"
        for left, right in sorted(duplicate_pairs)
    ]


def sensitive_log_calls(files: list[Path], root: Path) -> list[str]:
    findings: list[str] = []
    for path in files:
        lines = path.read_text(encoding="utf-8").splitlines()
        for index, line in enumerate(lines):
            if line.lstrip().startswith(("//", "///")) or not LOG_CALL_RE.search(line):
                continue
            statement_lines = [line]
            if ";" not in line:
                for following in lines[index + 1:index + 8]:
                    if following.lstrip().startswith(("//", "///")):
                        continue
                    statement_lines.append(following)
                    if ";" in following:
                        break
            statement = "\n".join(statement_lines)
            if SENSITIVE_RE.search(statement):
                relative = path.relative_to(root).as_posix()
                findings.append(f"possible sensitive logging at {relative}:{index + 1}")
    return findings


def validate_source(root: Path, window_size: int = 60) -> list[str]:
    files = source_files(root)
    errors = duplicate_blocks(files, root, window_size)
    errors.extend(sensitive_log_calls(files, root))
    if not files:
        errors.append("no governed C# source files were found")
    return errors


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--duplicate-window", type=int, default=60)
    args = parser.parse_args()
    root = args.root.resolve()
    if args.duplicate_window < 20:
        print("ERROR: duplicate window must be at least 20 tokens", file=sys.stderr)
        return 2
    errors = validate_source(root, args.duplicate_window)
    if errors:
        for error in errors:
            print(f"ERROR: {error}")
        return 1
    print(f".NET source policy passed ({len(source_files(root))} C# files scanned).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
