#!/usr/bin/env python3
"""Fail closed on hand-written, sensitive, or business-capable SDK source."""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE_FILES = (
    "packages/sdk/assetlink/dotnet/AssetLink.Generated.cs",
    "packages/sdk/assetlink/typescript/src/generated.ts",
    "packages/sdk/assetlink/kotlin/src/main/kotlin/app/assetlibrary/assetlink/AssetLink.Generated.kt",
)
SOURCE_GLOBS = {
    "packages/sdk/assetlink/dotnet": "*.cs",
    "packages/sdk/assetlink/typescript/src": "*.ts",
    "packages/sdk/assetlink/kotlin/src/main": "*.kt",
}
GENERATED_MARKER = "<auto-generated"
IGNORED_DIRECTORIES = {".gradle", "bin", "build", "dist", "node_modules", "obj"}
FORBIDDEN_PATTERNS = {
    ".cs": (
        r"\bSystem\.(?:IO|Net)\b",
        r"\b(?:File|Directory|HttpClient|Registry|NpgsqlConnection)\s*[.(]",
    ),
    ".ts": (
        r"(?:from|require\s*\()\s*[\"']node:(?:fs|http|https|net|path)",
        r"\b(?:fetch|XMLHttpRequest)\s*\(",
    ),
    ".kt": (
        r"\bjava\.(?:io|net|nio\.file)\b",
        r"\b(?:File|URL|Socket|OkHttpClient|Retrofit)\s*\(",
    ),
}
BUSINESS_POLICY_RE = re.compile(
    r"\b(?:PermissionPolicy|TransferStateMachine|SyncStateMachine|TrashPolicy|"
    r"OperationPlanExecutor|PhysicalPathPolicy)\b",
    re.IGNORECASE,
)
LOG_CALL_RE = re.compile(
    r"\b(?:Console\.(?:Write|WriteLine)|console\.(?:log|info|warn|error)|println|"
    r"[A-Za-z_][A-Za-z0-9_]*Logger\.(?:Log[A-Za-z]*|BeginScope)|logger\.(?:Log[A-Za-z]*|BeginScope))\s*\(",
    re.IGNORECASE,
)
SENSITIVE_RE = re.compile(
    r"password|passwd|secret|token|authorization|cookie|credential|api[_-]?key",
    re.IGNORECASE,
)


def validate_source(root: Path) -> list[str]:
    root = root.resolve()
    errors: list[str] = []
    expected = {root / relative for relative in SOURCE_FILES}
    discovered: set[Path] = set()
    for relative, pattern in SOURCE_GLOBS.items():
        base = root / relative
        if base.exists():
            discovered.update(
                path
                for path in base.rglob(pattern)
                if path.is_file()
                and not any(part.lower() in IGNORED_DIRECTORIES for part in path.relative_to(base).parts)
            )
    for path in sorted(expected):
        relative = path.relative_to(root).as_posix()
        if not path.is_file():
            errors.append(f"missing generated SDK source: {relative}")
            continue
        text = path.read_text(encoding="utf-8")
        if GENERATED_MARKER not in text[:512].lower():
            errors.append(f"SDK source lacks generated marker: {relative}")
        for pattern in FORBIDDEN_PATTERNS[path.suffix.lower()]:
            if re.search(pattern, text, flags=re.IGNORECASE):
                errors.append(f"generated SDK source contains forbidden I/O or network capability: {relative}")
                break
        if BUSINESS_POLICY_RE.search(text):
            errors.append(f"generated SDK source duplicates an application/core business policy: {relative}")
        lines = text.splitlines()
        for index, line in enumerate(lines, start=1):
            if LOG_CALL_RE.search(line) and SENSITIVE_RE.search(line):
                errors.append(f"possible sensitive logging in generated SDK source: {relative}:{index}")
    for path in sorted(discovered - expected):
        errors.append(f"unexpected SDK source outside the single generated file: {path.relative_to(root).as_posix()}")
    return errors


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT)
    args = parser.parse_args()
    errors = validate_source(args.root)
    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1
    print(f"AssetLink SDK source policy passed ({len(SOURCE_FILES)} generated source files).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
